code/config/routes.rb
Rails.application.routes.draw do


  #resources :likes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users/list_questions', to: 'questions#list_my_questions'
  get '/users/account', to: 'users#account'
  get '/users/edit_info', to: 'users#update'
  resources :questions do
    resources :answers do
      resources :comments
    end
  end

  resources :answers do
    resources :likes
  end

  root :to => 'questions#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/app/models/answer.rb
class Answer < ApplicationRecord
  validates :content,  presence: true
  has_many :comments
  belongs_to :question
  belongs_to :user
end

code/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    @question=Question.find(params[:question_id])
    @answer.question=@question

    @answer.user=current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render "questions/show" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_answers_path(@answer.question_id), notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:content, :question_id)
    end
end

code/app/helpers/answers_helper.rb
module AnswersHelper
end

code/app/views/answers/_answer.html.erb
<div>
  <p>
    <strong><%= time_ago_in_words(answer.created_at) %></strong>
    <br>
    <%= answer.content %>
  </p>
</div>

code/app/views/answers/_form.html.erb
<%= form_for [answer.question,answer] ,url: {action: "update"} do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code/app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', question_answer_path(@answer.question_id,@answer.id) %> |
<%= link_to 'Back', question_answers_path(@answer.question_id) %>

code/app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= link_to 'Show', question_answer_path(answer.question_id,answer.id) %></td>
        <td><%= link_to 'Edit', edit_question_answer_path(answer.question_id,answer.id) %></td>
        
        <td><%= link_to 'Destroy', question_answers_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_question_answer_path %>
<%= link_to 'Back', question_path(params[:question_id]) %>

code/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

code/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>


<%= link_to 'Edit', edit_question_answer_path(@answer.question_id,@answer.id) %> |
<%= link_to 'Back', question_answers_path(@answer.question_id) %>




<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @answer.comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= link_to 'Show', question_answer_comment_path(comment.answer.question_id, comment.answer.id,comment.id) %></td>
      <td><%= link_to 'Edit', edit_question_answer_comment_path(comment.answer.question_id, comment.answer.id,comment.id) %></td>
      <td><%= link_to 'Destroy', question_answer_comment_path(comment.answer.question_id, comment.answer.id,comment.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= form_for ([@answer.question,@answer, Comment.new]) do |f| %>
  <p>
    <%= f.label :content, "New Comment" %> <br />
    <%= f.text_area :content, :rows => 5 %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>