code/config/routes.rb
Rails.application.routes.draw do


  #resources :likes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users/list_questions', to: 'questions#list_my_questions'
  get '/users/account', to: 'users#account'
  get '/users/edit_info', to: 'users#update'
  resources :questions do
    resources :answers do
      resources :comments
    end
  end

  resources :answers do
    resources :likes
  end

  root :to => 'questions#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

code/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)
    @like.user = current_user
    @answer = Answer.find(params[:answer_id])
    @like.answer = @answer

    respond_to do |format|
      if @like.save
        format.html { redirect_to question_path(@answer.question_id), notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { render question_path(current_question.question_id), notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def like_params
    params.fetch(:like, {})
  end
end

code/app/helpers/likes_helper.rb
module LikesHelper
end

code/app/views/likes/_form.html.erb
<%= form_for ([@answer,Like.new]) do |form| %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

code/app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

code/app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
<!--        <td><%#= link_to 'Show', like %></td>-->
<!--        <td><%#= link_to 'Edit', edit_like_path(like) %></td>-->
<!--        <td><%#= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

code/app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

code/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>